.TH edfhed-gtk 1 "2012-01-11" 0.5.0 "Aghermann"
.SH NAME
	edfhed -- a simple EDF header viewer
.SH SYNOPSIS
	edfhed \fIfile.edf\fR
.B
.PP

.SH DESCRIPTION
.PP
\fBedfhed\fR is a terminal program which dumps the header of an EDF
file taken from the command line as the single arrgument.  It takes no options.

.SH SEE ALSO
aghermann(1), edfhed-gtk(1).

.SH AUTHOR
edfhed is written by Andrei Zavada <johnhommer@gmail.com> as part
of the Aghermann project.
